name: Fetch Data Daily

on:
  schedule:
    - cron: "0 0 * * *" # Tous les jours à minuit UTC

jobs:
  fetch_and_store:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # Étape 4 : Exécuter le script
      - name: Run Fetch and Store script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          API_URL: ${{ secrets.API_URL }}
        run: node scripts/fetchAndStoreData.js
